#!/bin/bash

# aoc [day] [input] [input]
# eg. aoc 14 test test2
# eg. aoc 14 1 1
# eg. aoc 14 1 2

if [ $# -ne 3 ]; then
    echo "Usage: aoc [day] [input] [input]"
    exit 1
fi

cd $AOC_PATH
cd $AOC_YEAR

day=$(printf "%02d" $1)
cd "day$day"

{ time python3 solver.py 1 $2 && time python3 solver.py 2 $3; } >log.txt 2>&1